name: treecrown-detection_detectreeRGB-full
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.3
  - asttokens=2.2.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.4
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.1.0
  - curl=8.1.2
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=1.2.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freetype=2.12.1
  - freexl=1.0.6
  - future=0.18.3
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - importlib-metadata=6.7.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.7.0
  - importlib_resources=5.12.0
  - ipykernel=6.23.3
  - ipython=8.12.2
  - jedi=0.18.2
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.1
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.16.0
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtiff=4.5.0
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2020.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - ninja=1.11.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.8.0
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pycurl=7.45.1
  - pygments=2.15.1
  - pyparsing=3.1.0
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.8.0
  - pyzmq=25.1.0
  - rasterio=1.3.6
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.42.0
  - stack_data=0.6.2
  - tiledb=2.13.2
  - tk=8.6.12
  - torchvision=0.9.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzcode=2023c
  - tzdata=2023c
  - unicodedata2=15.0.0
  - wcwidth=0.2.6
  - wheel=0.40.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asciitree==0.3.3
      - async-timeout==4.0.2
      - black==21.4b2
      - cachetools==5.3.1
      - cftime==1.6.2
      - charset-normalizer==3.1.0
      - cloudpickle==2.2.1
      - dask==2023.5.0
      - distinctipy==1.2.2
      - entrypoints==0.4
      - exifread==3.0.0
      - fasteners==0.18
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - fvcore==0.1.5.post20221221
      - google-auth==2.21.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.0
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.31.1
      - intake==0.7.0
      - intake-xarray==0.7.0
      - iopath==0.1.9
      - jinja2==3.1.2
      - lazy-loader==0.3
      - locket==1.0.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - msgpack==1.0.5
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - netcdf4==1.6.4
      - networkx==3.1
      - numcodecs==0.11.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.8.0.74
      - opencv-python-headless==4.8.0.74
      - pandas==1.5.3
      - partd==1.4.0
      - pathspec==0.11.1
      - pooch==1.7.0
      - portalocker==2.7.0
      - protobuf==4.23.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.6
      - pydantic==1.10.11
      - pydot==1.4.2
      - pyproj==3.5.0
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - regex==2023.6.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rioxarray==0.13.4
      - rsa==4.9
      - scikit-image==0.21.0
      - scipy==1.10.1
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - termcolor==2.3.0
      - tifffile==2023.7.4
      - toml==0.10.2
      - toolz==0.12.0
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - xarray==2023.1.0
      - yacs==0.1.8
      - yarl==1.9.2
      - zarr==2.15.0
      - scivision==0.7.0
      - detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6
      - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git
