name: treecrown-detection_detectreeRGB
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - ipykernel
  - matplotlib
  - pip
  - pycurl
  - pytorch==1.8.0
  - rasterio
  - torchvision==0.9.0
  - tqdm
  - urllib3
  - pooch
  - pip:
    - rioxarray 
    - git+https://github.com/alan-turing-institute/scivision.git@update-treecrown
    - detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6