name: treecrown-detection_detectreeRGB
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - ipykernel
  - matplotlib
  - pip
  - pycurl
  - pytorch==1.8.0
  - rasterio
  - torchvision==0.9.0
  - tqdm
  - urllib3
  - pip:
    - rioxarray 
    - scivision==0.7.0
    - detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6
    - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git@v2021.02.06.1
